services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/attendance
      CORS_ORIGINS: http://localhost:5173,http://localhost:8080,http://127.0.0.1:8080
      ONNX_PROVIDERS: CPUExecutionProvider
      FAISS_INDEX_PATH: /app/faiss_indexes/faces.index
      FAISS_META_PATH: /app/faiss_indexes/faces_meta.json
      INSIGHTFACE_HOME: /app/ai_models
      DET_SIZE_WIDTH: 320
      DET_SIZE_HEIGHT: 320
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../faiss_indexes:/app/faiss_indexes
      - ../ai_models:/app/ai_models
      # Mount code trực tiếp vào container để Auto-reload khi sửa code
      - ../backend/app:/app/app
    # Ghi đè lệnh chạy để bật tính năng tự khởi động lại (Reload)
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
